version : 0.0.2
container-name-run : "recipeservice"
container-name-tools : "bx-dev-recipeservice-tools"
image-name-run : "recipeservice"

image-name-tools : "bx-dev-java-maven-tools"
host-path-run : "target"
build-cmd-run : "mvn install -Dmaven.repo.local=/project/.m2/repository"
test-cmd : "mvn install -Dmaven.repo.local=/project/.m2/repository"
build-cmd-debug : "mvn install -Dmaven.repo.local=/project/.m2/repository"

container-path-run : "/project"
container-path-tools : "/project"

#Liberty server settings
container-port-map : "9080:9080,9443:9443"
container-port-map-debug : "7777:7777"
debug-cmd : "server debug"


dockerfile-run : "Dockerfile"
dockerfile-tools : "Dockerfile-tools"
ibm-generated-id : "65fb7674-d8bc-4e9e-b6e7-fe747d2677de"
credentials-filepath : "src/main/liberty/config/server.env, log.txt"